# Generated by Django 2.1.5 on 2022-06-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0003_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='course_files/')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.Course')),
            ],
        ),
    ]
