# Generated by Django 2.1.5 on 2022-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0007_auto_20220612_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
