# Generated by Django 2.0.7 on 2022-06-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220622_0841'),
        ('adminmodule', '0008_course_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='userCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.Course')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
