# Generated by Django 2.0.7 on 2022-06-28 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0011_auto_20220628_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cid', to='adminmodule.Course'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='student.Student'),
        ),
    ]
