# Generated by Django 2.0.7 on 2022-06-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_course'),
        ('adminmodule', '0013_auto_20220628_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='usercourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cid', to='adminmodule.Course')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uid', to='student.Student')),
            ],
        ),
    ]
