# Generated by Django 2.0.7 on 2022-06-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0015_auto_20220628_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='uid',
        ),
        migrations.DeleteModel(
            name='usercourse',
        ),
    ]
