# Generated by Django 2.0.7 on 2022-07-04 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0016_auto_20220628_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(default=' ', max_length=100)),
                ('date', models.CharField(default=' ', max_length=100)),
                ('time', models.CharField(default=' ', max_length=100)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Batch_videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='videos/')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminmodule.Batch')),
            ],
        ),
    ]
