# Generated by Django 2.0.7 on 2022-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0013_auto_20220628_2002'),
        ('student', '0003_auto_20220622_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='adminmodule.Course'),
        ),
    ]
