# Generated by Django 2.0.7 on 2022-06-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
