# Generated by Django 2.0.7 on 2022-06-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
