# Generated by Django 2.0.7 on 2022-07-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20220628_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(null=True, to='adminmodule.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='smobile',
            field=models.BigIntegerField(),
        ),
    ]
