# Generated by Django 2.0.7 on 2022-07-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20220704_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(blank=True, to='adminmodule.Course'),
        ),
    ]
