# Generated by Django 4.0.6 on 2022-07-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
