# Generated by Django 2.2.28 on 2022-07-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20220717_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
