# Generated by Django 4.0.6 on 2022-07-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminmodule', '0022_auto_20220717_2024'),
        ('student', '0016_auto_20220717_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ManyToManyField(blank=True, to='adminmodule.batch'),
        ),
    ]
